# Generated by Django 2.1.2 on 2018-10-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='testcategory',
            field=models.CharField(default='MS1', max_length=30),
        ),
    ]
